local tweenInfos = {}

tweenInfos.expo1out = TweenInfo.new(1, Enum.EasingStyle.Exponential, Enum.EasingDirection.Out)
tweenInfos.expo02out = TweenInfo.new(0.2, Enum.EasingStyle.Exponential, Enum.EasingDirection.Out)
tweenInfos.expo05out = TweenInfo.new(0.5, Enum.EasingStyle.Exponential, Enum.EasingDirection.Out)
tweenInfos.back05out = TweenInfo.new(0.5, Enum.EasingStyle.Back, Enum.EasingDirection.Out)

return tweenInfos
