-- English (United Kingdom)

local lang = {} 

lang.code = "en_UK"

lang.DevToolsTitle = "DevTools"
lang.Luatri = "Luatri"
lang.ParticleCulling = "Particle culling"
lang.InteriorCulling = "Interior culling"


lang.DebugOutputs = "Debug outputs"

lang.OutputLuatriParticles = "Luatri particle culling"
lang.OutputLuatriInterior = "Luatri interior culling"
lang.OutputLuatriInteriorVerbose = "Luatri verbose interior culling"


lang.SampleButtons = "Sample buttons"

lang.SampleButtonTitle = "Hi!"
lang.SampleButtonTooltip = "Add your own buttons in the DevTools script! :)"


lang.TestOutputs = "Test outputs"

lang.NormalOutputTitle = "Normal output"
lang.NormalOutputTooltip = "A normal level output"

lang.WarnOutputTitle = "Warn output"
lang.WarnOutputTooltip = "A warning level output"

lang.WarnOutputTitle = "Error output"
lang.WarnOutputTooltip = "A danger level output"



return lang