-- English (United States)

local lang = {} 

lang.code = "en_US"

lang.DevToolsTitle = "DevTools"
lang.Luatri = "Luatri"
lang.ParticleCulling = "Particle Culling"
lang.InteriorCulling = "Interior Culling"


lang.DebugOutputs = "Debug Outputs"

lang.OutputLuatriParticles = "Luatri Particle Culling"
lang.OutputLuatriInterior = "Luatri Interior Culling"
lang.OutputLuatriInteriorVerbose = "Luatri Verbose Interior Culling"


lang.SampleButtons = "Sample Buttons"

lang.SampleButtonTitle = "Hi!"
lang.SampleButtonTooltip = "Add your own buttons in the DevTools script! :)"


lang.TestOutputs = "Test Outputs"

lang.NormalOutputTitle = "Normal Output"
lang.NormalOutputTooltip = "A normal level output"

lang.WarnOutputTitle = "Warn Output"
lang.WarnOutputTooltip = "A warning level output"

lang.ErrorOutputTitle = "Error Output"
lang.ErrorOutputTooltip = "A danger level output"



return lang