-- Latvian

local lang = {} 

lang.code = "lv_LV"

lang.DevToolsTitle = "Izstrādātāju rīki"
lang.Luatri = "Luatri"
lang.ParticleCulling = "Daļiņu izkaušana"
lang.InteriorCulling = "Interjeras izkaušana"


lang.DebugOutputs = "Atkļūdošanas izvades"

lang.OutputLuatriParticles = "Luatri daļiņu izkaušana"
lang.OutputLuatriInterior = "Luatri interjeras izkaušana"
lang.OutputLuatriInteriorVerbose = "Luatri precīza interjeras izkaušana"


lang.SampleButtons = "Parauga pogas"

lang.SampleButtonTitle = "Sveiki!"
lang.SampleButtonTooltip = "Pievienojiet savas pogas izstrādātāju rīka skriptam! :)"


lang.TestOutputs = "Testa izvades"

lang.NormalOutputTitle = "Normāla izvade"
lang.NormalOutputTooltip = "Normāla līmeņa izvade"

lang.WarnOutputTitle = "Brīdinājuma izvade"
lang.WarnOutputTooltip = "Brīdinājuma līmeņa izvade"

lang.ErrorOutputTitle = "Kļūdu izvade"
lang.ErrorOutputTooltip = "Bīstama līmeņa izvade"



return lang