-- Russian

local lang = {} 

lang.code = "ru_RU"

lang.DevToolsTitle = "Инструменты разработчика"
lang.Luatri = "Луатри"
lang.ParticleCulling = "Oтбраковка частиц"
lang.InteriorCulling = "Внутренняя выбраковка"


lang.DebugOutputs = "Выходные данные отладки"

lang.OutputLuatriParticles = "Луатри oтбраковка частиц"
lang.OutputLuatriInterior = "Луатри внутренняя выбраковка"
lang.OutputLuatriInteriorVerbose = "Луатри подробная внутренняя выбраковка"


lang.SampleButtons = "Образцы кнопок"

lang.SampleButtonTitle = "Привет!"
lang.SampleButtonTooltip = "Добавьте свои собственные кнопки в скрипт DevTools! :)"


lang.TestOutputs = "Тестовые результаты"

lang.NormalOutputTitle = "Нормальный вывод"
lang.NormalOutputTooltip = "Выход нормального уровня"

lang.WarnOutputTitle = "Выход предупреждения"
lang.WarnOutputTooltip = "Выходной уровень предупреждения"

lang.WarnOutputTitle = "Ошибка вывода"
lang.WarnOutputTooltip = "Выходной уровень ошибки"



return lang